/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg8quanhau;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Hassasin
 */
public class Image_1 extends javax.swing.JFrame {

    /**
     * Creates new form Image
     */
    BufferedImage imageB=null,imageW=null,imageQ=null,imageWalp=null,imageT=null,imageF=null;
    ArrayList<String> key_data;//giá trị mảng key trong InterFace hiện tại
    ArrayList<String> pos_data;//Vị trí đang xét và giá trị của nó
    //
    private String key,pos;
    private int i=0,n;
    //
    Input a=new Input();
    //
    public Image_1() {
        initComponents();
        key_data=a.getKey();
        pos_data=a.getPos();
    }
    
    
    public void setKey_data(ArrayList<String> key_data) {
        this.key_data = key_data;
    }
    
    public void setN(int n) {
        this.n = n;
    }
    
    public void setPos_data(ArrayList<String> pos_data) {
        this.pos_data = pos_data;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bàn cờ mô phỏng");
        setFocusableWindowState(false);

        jLabel1.setText("abcs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public void paint(Graphics g) {        
        try {
            imageWalp=new BufferedImage(60,60,BufferedImage.TYPE_INT_ARGB);
            imageWalp=ImageIO.read(new File("D:\\Code\\Java\\NetBeans\\8QuanHau\\src\\pkg8quanhau\\wallpaper.png"));
            imageB=new BufferedImage(60,60,BufferedImage.TYPE_INT_ARGB);
            imageB=ImageIO.read(new File("D:\\Code\\Java\\NetBeans\\8QuanHau\\src\\pkg8quanhau\\black.png"));
            imageW=new BufferedImage(60,60,BufferedImage.TYPE_INT_ARGB);
            imageW=ImageIO.read(new File("D:\\Code\\Java\\NetBeans\\8QuanHau\\src\\pkg8quanhau\\white.png"));
            imageQ=new BufferedImage(60,60,BufferedImage.TYPE_INT_ARGB);
            imageQ=ImageIO.read(new File("D:\\Code\\Java\\NetBeans\\8QuanHau\\src\\pkg8quanhau\\queen.png"));
            imageT=new BufferedImage(60,60,BufferedImage.TYPE_INT_ARGB);
            imageT=ImageIO.read(new File("D:\\Code\\Java\\NetBeans\\8QuanHau\\src\\pkg8quanhau\\CrossRed.png"));
            imageF=new BufferedImage(60,60,BufferedImage.TYPE_INT_ARGB);
            imageF=ImageIO.read(new File("D:\\Code\\Java\\NetBeans\\8QuanHau\\src\\pkg8quanhau\\CrossGreen.png"));
            } catch (IOException ex) {
                Logger.getLogger(InterFace.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    //Creat_bàn_cờ
        System.out.println("Start Creat Bàn cờ:");
        g.drawImage(imageWalp,0, 0, 60*(n+2), 60*(n+2), null);      
        for (int i=0;i<n;i++){
            for (int j=0;j<n;j++){
            if ((i+j)%2!=0) g.drawImage(imageB, i*60+60, j*60+60, 60, 60, null);
            else g.drawImage(imageW, i*60+60, j*60+60, 60, 60, null);
            }
        }
        System.out.println("Creat Bàn Cờ Succesful!");
        //repaint(g);            
        try {
                Thread.sleep(2000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Image_1.class.getName()).log(Level.SEVERE, null, ex);
            }
        update(g);
    }
    public void update(Graphics g){
        
        if (i<key_data.size()){
            System.out.println("Creat lần "+i);
            key=key_data.get(i);
            pos=pos_data.get(i);
            i++;
            System.out.println("In ra "+i);
            
    //Creat_Quân_hậu
            ArrayList<Integer> a=reformat(key);        
            for (int j=1;j<a.size();j++){
                if (a.get(j)!=0) g.drawImage(imageQ, a.get(j)*60,j*60+60, 60, 60, null);
            }            
    //Creat_đang_xét
        ArrayList<Integer> b=reformat(pos);
        if (b.get(2)==0) g.drawImage(imageF, b.get(0)*60, b.get(1)*60, 60, 60, null);
        else g.drawImage(imageT, b.get(0)*60, b.get(1)*60, 60, 60, null);
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(Image_1.class.getName()).log(Level.SEVERE, null, ex);
            }
        update(g);
        //repaint(g);
        }
    }
    
    public ArrayList<Integer> reformat(String key){// chuyển String sang ArrayList tương ứng
        ArrayList<Integer> a=new ArrayList();
        for (int i=0;i<key.length();i++){
            if (key.charAt(i)!=' '){
                String b="";
                while(key.charAt(i)!=' ') {b=b+key.charAt(i++);if (i==key.length()) break;}
                a.add(Integer.valueOf(b));
            }
        }
        return a;
    }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Image(0,"").setVisible(true);
            }
        });
    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
