/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg8quanhau;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Hassasin
 */
public class Image extends javax.swing.JFrame {

    /**
     * Creates new form Image
     */
    BufferedImage imageB=null,imageW=null,imageQ=null,imageWalp=null;
    String key;//giá trị mảng key trong InterFace hiện tại
    String pos;//Vị trí đang xét và giá trị của nó
    public Image(int n,String a) {
        this.n=n;
        this.key=a;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bàn cờ mô phỏng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private int n; 
    public void paint(Graphics g) {        
        try {
            imageWalp=new BufferedImage(60,60,BufferedImage.TYPE_INT_ARGB);
            imageWalp=ImageIO.read(new File("D:\\Code\\Java\\NetBeans\\8QuanHau\\src\\pkg8quanhau\\wallpaper.png"));
            imageB=new BufferedImage(60,60,BufferedImage.TYPE_INT_ARGB);
            imageB=ImageIO.read(new File("D:\\Code\\Java\\NetBeans\\8QuanHau\\src\\pkg8quanhau\\black.png"));
            imageW=new BufferedImage(60,60,BufferedImage.TYPE_INT_ARGB);
            imageW=ImageIO.read(new File("D:\\Code\\Java\\NetBeans\\8QuanHau\\src\\pkg8quanhau\\white.png"));
            imageQ=new BufferedImage(60,60,BufferedImage.TYPE_INT_ARGB);
            imageQ=ImageIO.read(new File("D:\\Code\\Java\\NetBeans\\8QuanHau\\src\\pkg8quanhau\\queen.png"));
            g.drawImage(imageWalp,0, 0, 60*(n+2), 60*(n+2), null);
            
            for (int i=0;i<n;i++){
                for (int j=0;j<n;j++){
                if ((i+j)%2!=0) g.drawImage(imageB, i*60+60, j*60+60, 60, 60, null);
                else g.drawImage(imageW, i*60+60, j*60+60, 60, 60, null);
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(InterFace.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ArrayList<Integer> a=new ArrayList();
        for (int i=0;i<key.length();i++){
            if (key.charAt(i)!=' '){
                String b="";
                while(key.charAt(i)!=' ') {b=b+key.charAt(i++);if (i==key.length()) break;}
                a.add(Integer.valueOf(b));
            }
        }
        for (int i=0;i<a.size();i++){
            g.drawImage(imageQ, a.get(i)*60,i*60+60, 60, 60, null);
        }
        
        //repaint(g);
    }
    
    public void repaint(Graphics g){
        g.drawImage(imageQ, 60, 60, 60, 60, null);
    }
    /*
    public void paintComponent(Graphics g){
        super.paintComponents(g);
        g.drawImage(imageQ, 0, 0, 60, 60, null);
    }
    public void paintImage(){
        repaint();
    }
    */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Image(0,"").setVisible(true);
            }
        });
    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
